### PR TITLE
Add "Alphabetically by name" option in Gradle dependency sorting strategy

### PR DESCRIPTION
**Pull request by sunhong**
Added a new option to sort the dependencies by their names rather than the whole class paths.
This update is related to this discussion -
https://github.com/spring-projects/eclipse-integration-gradle/issues/2

### CODE REVIEW

**Comment by sunhong** [comment]
image

**Comment by BoykoAlex** [comment]
Do you mind removing formatting/blank space changes? It's too many of them and difficult to track what's being changed... I suspect that you change far less code then Git shows...

**Comment by sunhong** [comment]
Sure, I will solve the formatting issue. Thanks

**Comment by BoykoAlex** [comment]
Did you sign the CLA yet? This is the link: https://support.springsource.com/spring_eclipsecla_committer_signup Please sign it - takes a minute. This is for us to be able to accept your contributions.

**Pull request closed without merging**
